### ISSUE TITLE
Window for Nexus weapon is too small

### ISSUE THREAD

**Issue by RedKitsune** [daemitus/ZodiacBuddy#15]
When trying to upgrade my Nexus weapon for my WAR, all i see in the window is the name of the weapon and I barely see some purple indicating that the progress bar is here but not visible (same with the bonus light dungeon) :
![image](https://user-images.githubusercontent.com/2812637/179631072-be88362f-073b-4009-b649-d114e2ec0734.png)

Is it possible to make the window bigger like the one for the Novus stage ?

**Comment by daemitus** [comment]
lmao. im going to have to login and test this for once :D

**Comment by Hiroa** [comment]
I don't know how, but after lot of random manipulation, I manage to reproduct it

> 2022-07-19 23:52:44.596 +02:00 [ERR] [ZodiacBuddy] UiBuilder OnBuildUi caught exception
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ImGuiNET.ImGuiNative.igPopItemWidth()
   at ZodiacBuddy.ConfigWindow.DrawBrave()
   at Dalamud.Interface.Windowing.Window.DrawInternal() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 200
   at Dalamud.Interface.Windowing.WindowSystem.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 117
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 473


I forgot to remove the ImGui.PopItemWidth(); (and separator) here. ZodiacBuddy\ConfigWindow.cs:210

**Comment by RedKitsune** [comment]
All good for me after the latest update ! Thank you very much for it, it really helped for completing the weapon =)
